# Generated by Django 5.2.8 on 2025-11-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_glucose_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_glucose_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_glucose_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_glucose_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_is_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_is_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_trend',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
